// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayHard.Data;

#nullable disable

namespace StayHard.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240116230517_StayHardDB")]
    partial class StayHardDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StayHard.Data.Models.Grad", b =>
                {
                    b.Property<int>("GradID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradID"));

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivGrada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradID");

                    b.ToTable("Grad");
                });

            modelBuilder.Entity("StayHard.Data.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"));

                    b.Property<int>("BMI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OsobaID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isVIP")
                        .HasColumnType("bit");

                    b.HasKey("KorisnikID");

                    b.HasIndex("OsobaID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("StayHard.Data.Models.KorisnikPlan", b =>
                {
                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrajanjePretplate")
                        .HasColumnType("datetime2");

                    b.HasKey("PlanID", "KorisnikID");

                    b.ToTable("KorisnikPlan");
                });

            modelBuilder.Entity("StayHard.Data.Models.KreditnaKartica", b =>
                {
                    b.Property<int>("KarticaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KarticaID"));

                    b.Property<string>("BrojKartice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<string>("SigurnosniBroj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KarticaID");

                    b.ToTable("KreditnaKartica");
                });

            modelBuilder.Entity("StayHard.Data.Models.KupovinaPlana", b =>
                {
                    b.Property<int>("KupovinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KupovinaID"));

                    b.Property<int>("KarticaID")
                        .HasColumnType("int");

                    b.Property<int>("KreditnaKarticaKarticaID")
                        .HasColumnType("int");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("PlanTreningaPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeKupovine")
                        .HasColumnType("datetime2");

                    b.HasKey("KupovinaID");

                    b.HasIndex("KreditnaKarticaKarticaID");

                    b.HasIndex("PlanTreningaPlanID");

                    b.ToTable("KupovinaPlana");
                });

            modelBuilder.Entity("StayHard.Data.Models.Osoba", b =>
                {
                    b.Property<int>("OsobaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OsobaID"));

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KarticaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("OsobaID");

                    b.HasIndex("GradId");

                    b.HasIndex("KarticaID");

                    b.ToTable("Osoba");
                });

            modelBuilder.Entity("StayHard.Data.Models.PlanTreninga", b =>
                {
                    b.Property<int>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TipID")
                        .HasColumnType("int");

                    b.Property<int>("TrenerID")
                        .HasColumnType("int");

                    b.HasKey("PlanID");

                    b.HasIndex("TrenerID");

                    b.ToTable("PlanTreninga");
                });

            modelBuilder.Entity("StayHard.Data.Models.Recenzija", b =>
                {
                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecenzijaID")
                        .HasColumnType("int");

                    b.Property<int>("Vrijednost")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("KorisnikID", "PlanID");

                    b.ToTable("Recenzija");
                });

            modelBuilder.Entity("StayHard.Data.Models.SadrzajPlana", b =>
                {
                    b.Property<int>("SadrzajID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SadrzajID"));

                    b.Property<string>("Dan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanID")
                        .HasColumnType("int");

                    b.Property<int>("PlanTreningaPlanID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("SadrzajID");

                    b.HasIndex("PlanTreningaPlanID");

                    b.ToTable("SadrzajPlana");
                });

            modelBuilder.Entity("StayHard.Data.Models.TipTreninga", b =>
                {
                    b.Property<int>("TipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipID");

                    b.ToTable("TipTreninga");
                });

            modelBuilder.Entity("StayHard.Data.Models.Trener", b =>
                {
                    b.Property<int>("TrenerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrenerID"));

                    b.Property<string>("Certifikat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Struka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrenerID");

                    b.ToTable("Trener");
                });

            modelBuilder.Entity("StayHard.Data.Models.Korisnik", b =>
                {
                    b.HasOne("StayHard.Data.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");
                });

            modelBuilder.Entity("StayHard.Data.Models.KupovinaPlana", b =>
                {
                    b.HasOne("StayHard.Data.Models.KreditnaKartica", "KreditnaKartica")
                        .WithMany()
                        .HasForeignKey("KreditnaKarticaKarticaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayHard.Data.Models.PlanTreninga", "PlanTreninga")
                        .WithMany()
                        .HasForeignKey("PlanTreningaPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KreditnaKartica");

                    b.Navigation("PlanTreninga");
                });

            modelBuilder.Entity("StayHard.Data.Models.Osoba", b =>
                {
                    b.HasOne("StayHard.Data.Models.Grad", "Grad")
                        .WithMany()
                        .HasForeignKey("GradId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StayHard.Data.Models.KreditnaKartica", "KreditnaKartica")
                        .WithMany()
                        .HasForeignKey("KarticaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grad");

                    b.Navigation("KreditnaKartica");
                });

            modelBuilder.Entity("StayHard.Data.Models.PlanTreninga", b =>
                {
                    b.HasOne("StayHard.Data.Models.Trener", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("StayHard.Data.Models.SadrzajPlana", b =>
                {
                    b.HasOne("StayHard.Data.Models.PlanTreninga", "PlanTreninga")
                        .WithMany()
                        .HasForeignKey("PlanTreningaPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanTreninga");
                });
#pragma warning restore 612, 618
        }
    }
}
